"""empty message

Revision ID: 136682d31139
Revises: 68c47b399dfc
Create Date: 2023-03-22 23:17:36.300148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136682d31139'
down_revision = '68c47b399dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
