"""empty message

Revision ID: 68c47b399dfc
Revises: c01b9c744434
Create Date: 2023-03-22 23:13:11.095478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c47b399dfc'
down_revision = 'c01b9c744434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preparation_time', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('preparation_time')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
