"""empty message

Revision ID: b00707f0583d
Revises: ceb91b3c432a
Create Date: 2023-03-26 23:18:03.526404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00707f0583d'
down_revision = 'ceb91b3c432a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('rating')

    op.drop_table('favorite')
    # ### end Alembic commands ###
